class Lists {
  static List<String> citiesilkderece = [
    'Adana',
    'Adıyaman',
    'Afyonkarahisar',
    'Ağrı',
    'Aksaray',
    'Amasya',
    'Ankara',
    'Antalya',
    'Ardahan',
    'Artvin',
    'Aydın',
    'Balıkesir',
    'Bartın',
    'Batman',
    'Bayburt',
    'Bilecik',
    'Bingöl',
    'Bitlis',
    'Bolu',
    'Burdur',
    'Bursa',
    'Çanakkale',
    'Çankırı',
    'Çorum',
    'Denizli',
    'Diyarbakır',
    'Düzce',
    'Edirne',
    'Elazığ',
    'Erzincan',
    'Erzurum',
    'Eskişehir',
    'Gaziantep',
    'Giresun',
    'Gümüşhane',
    'Hakkari',
    'Hatay',
    'Iğdır',
    'Isparta',
    'İstanbul',
    'İzmir',
    'Kahramanmaraş',
    'Karabük',
    'Karaman',
    'Kars',
    'Kastamonu',
    'Kayseri',
    'Kırıkkale',
    'Kırklareli',
    'Kırşehir',
    'Kilis',
    'Kocaeli',
    'Konya',
    'Kütahya',
    'Malatya',
    'Manisa',
    'Mardin',
    'Mersin',
    'Muğla',
    'Muş',
    'Nevşehir',
    'Niğde',
    'Ordu',
    'Osmaniye',
    'Rize',
    'Sakarya',
    'Samsun',
    'Siirt',
    'Sinop',
    'Sivas',
    'Şanlıurfa',
    'Şırnak',
    'Tekirdağ',
    'Tokat',
    'Trabzon',
    'Tunceli',
    'Uşak',
    'Van',
    'Yalova',
    'Yozgat',
    'Zonguldak'
  ];
   static List<String> citiesbolgeidare = [
    'Adana',
    'Ankara',
    'Bursa',
    'Erzurum',
    'Gaziantep',
    'İstanbul',
    'İzmir',
    'Konya',
    'Samsun'
  ];
   static List<String> citiesbolgeadliye = [
    'Adana',
    'Ankara',
    'Antalya',
    'Bursa',
    'Erzurum',
    'Gaziantep',
    'İstanbul',
    'İzmir',
    'Konya',
    'Kayseri',
    'Sakarya',
    'Tekirdağ',
    'Van',
    'Denizli',
    'Diyarbakır',
    'Samsun',
    'Trabzon'
  ];
 static List<String> courtsilkderece= [
    'Asliye Hukuk Mahkemesi',
    'Sulh Hukuk Mahkemesi',
    'Tüketici Mahkemeleri',
    'Aile Mahkemesi',
    'İş Mahkemesi',
    'İcra Mahkemesi',
    'Asliye Ticaret Mahkemeleri',
    'Sulh Ceza Mahkemeleri',
    'Asliye Ceza Mahkemeleri',
    'Ağır Ceza Mahkemeleri',
    'İdare Mahkemeleri',
    'Vergi Mahkemeleri',
    'Fikri ve Sınai Haklar Hukuk Mahkemeleri',
    'Kadastro Mahkemeleri'
  ];
 static List<String> courtsbolgeidare = [
    'İdari Dava Dairesi',
    'Vergi Dava Dairesi',
    
  ];
 static List<String> courtsbolgeadliye = [
    'Ceza Dairesi',
    'Hukuk Dairesi',
    
  ];
 static List<String> courtsyargitay = [
    '1. Ceza Dairesi',
    '2. Ceza Dairesi',
    '3. Ceza Dairesi',
    '4. Ceza Dairesi',
    '5. Ceza Dairesi',
    '6. Ceza Dairesi',
    '7. Ceza Dairesi',
    '8. Ceza Dairesi',
    '9. Ceza Dairesi',
    '10. Ceza Dairesi',
    '11. Ceza Dairesi',
    '12. Ceza Dairesi',
    '13. Ceza Dairesi',
    '14. Ceza Dairesi',
    '15. Ceza Dairesi',
    '16. Ceza Dairesi',
    '17. Ceza Dairesi',
    '18. Ceza Dairesi',
    '19. Ceza Dairesi',
    '20. Ceza Dairesi',
    '21. Ceza Dairesi',
    '22. Ceza Dairesi',
    '1. Hukuk Dairesi',
    '2. Hukuk Dairesi',
    '3. Hukuk Dairesi',
    '4. Hukuk Dairesi',
    '5. Hukuk Dairesi',
    '6. Hukuk Dairesi',
    '7. Hukuk Dairesi',
    '8. Hukuk Dairesi',
    '9. Hukuk Dairesi',
    '10. Hukuk Dairesi',
    '11. Hukuk Dairesi',
    '12. Hukuk Dairesi',
    '13. Hukuk Dairesi',
    '14. Hukuk Dairesi',
    '15. Hukuk Dairesi',
    '16. Hukuk Dairesi',
    '17. Hukuk Dairesi',
    '18. Hukuk Dairesi',
    '19. Hukuk Dairesi',
    '20. Hukuk Dairesi',
    'Hukuk Genel Kurulu',
    'Ceza Genel Kurulu',
    
  ];
 static List<String> courtsdanistay = [
    'Danıştay 1. Daire Başkanlığı',
    'Danıştay 2. Daire Başkanlığı',
    'Danıştay 3. Daire Başkanlığı',
    'Danıştay 4. Daire Başkanlığı',
    'Danıştay 5. Daire Başkanlığı',
    'Danıştay 6. Daire Başkanlığı',
    'Danıştay 7. Daire Başkanlığı',
    'Danıştay 8. Daire Başkanlığı',
    'Danıştay 9. Daire Başkanlığı',
    'Danıştay 10. Daire Başkanlığı',
    'Danıştay 11. Daire Başkanlığı',
    'Danıştay 12. Daire Başkanlığı',
    'Danıştay 13. Daire Başkanlığı',
    'Danıştay 14. Daire Başkanlığı',
    'Danıştay 15. Daire Başkanlığı',
    'Danıştay İdari Dava Daireleri Kurulu',
    'Danıştay Vergi Dava Daireleri Kurulu',
    
  ];
}
